### ISSUE TITLE
Browser Plugin - on pop state error handling

### ISSUE THREAD

**Issue by olegomon** [router5/router5#129]
I was experimenting with `canDeactivate` handlers and noticed some behaviour I couldn't understand. On `CANNOT_DEACTIVATE` errors which were caused after a `popstate` event by pressing the browser back button, the URL in the browser changed according to the history entry and - as expected  - the router state didn't change because the transition didn't pass the `canDeactivate` handler. So the router state and the browser url were not in sync anymore.

I looked through the code and correct me if I'm wrong but usually the error object in Router5 code base has always two properties `code` and `segment` but in the browser module at [line 70](https://github.com/router5/router5/blob/master/modules/plugins/browser/index.js#L70) the error is compared to a string constant from `errorCodes.CANNOT_DEACTIVATE` and the code in that if block is never executed?

Should't the condition be something like that? `if(err.code === errorCodes.CANNOT_DEACTIVATE) { ... }`

BTW: Very nice work you've done here. Well written code, easy to read and easy to understand! Thanks to you and all contributors!

**Comment by troch** [comment]
Hi @olegomon,

Will look at it when I have a bit more time (busy moving house just now). Thanks for your kind words! :+1: 

On a side note, `canDeactivate` and `browserPlugin` are not good friends, because history `popstate` events are not cancellable (I recommend using `forceDeactivate: true` in browser plugin options).
