### ISSUE TITLE
Scroll restoration

### ISSUE THREAD

**Issue by satazor** [router5/router5#130]
Hello! I'm evaluating this library as an alternative to react-router and it looks quite good!

I've looked in the documentation and examples but couldn't find anything about scroll restoration.
I've cloned the examples repository to see if scroll position was restored when navigating back & forward and it seems it does not (tested this by making the `Compose` component have `1000px` height).

Perhaps this functionality could live into a plugin, possibly by using https://github.com/taion/scroll-behavior. Thoughts?

Thanks

**Comment by troch** [comment]
Hi @satazor,

router5 is no concerned by rendering, so scroll restoration is outwith its responsibilities. Scroll restoration is fairly straight forward, you "just" need to track scroll, persist it and restore it. I've not done it with router5, and a solution would be depending on how you render components. I can think of several ways:

- If you can store that information somewhere which is not the router itself (redux store, in a container component with local state like your root node, any stores...), then you don't need to involve router5 at all.
- Middlewares could be an option, you could "enhance" the router state by adding custom information (scroll depth). But you have to be careful since you wouldn't be able to stop listening to window scroll events.
- Plugins: you can listen / stop listening to scroll events. However sharing that state could be tricky. It all depends on your implementation. If you are using redux for example, then you could create your own plugin which sends the state to the redux store, rather than using `redux-router5` plugin (https://github.com/router5/redux-router5/blob/master/modules/lib/reduxPlugin.js).

**Comment by satazor** [comment]
Thank you for the suggestions.

I'm still looking into a alternative router and if we stick with router5 I will definitely look into implementing this. I will share the solution so that you could possible add to the list of integrations / plugins.

**Comment by tomsdev** [comment]
Hey @satazor, did you make any progress on this?

**Comment by satazor** [comment]
No sorry, I've been overwhelmed with work but it's something I want to do

**Comment by titouancreach** [comment]
I'm going to implement this myself for a specific need. If someone has done this before, it would be nice to upload the code here :)

**Comment by LeonardoGentile** [comment]
@titouancreach wouldn't this be a good fit for a separate plugin?

**Comment by titouancreach** [comment]
Yes probably, for now, I've a simple HOC that save the scroll when componentWillUnmount() and restore it when componentDidMount() it could be enough for 90% of the case and it not tied to router5

**Comment by LeonardoGentile** [comment]
@titouancreach where do you store the scroll info? In redux or similar?

**Comment by titouancreach** [comment]
I did this with the context API, but yes, it's similar to any store
