### ISSUE TITLE
Reload and Replace options Default values

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#148]
Hello,
I've looked at the documentation and it's not very clear where (sometimes) the default values for navigation options comes from.

From the docs: `router.navigate(routeName, [routeParams], [options], [done])` where options is an object in the form

```
{ replace: bool, reload: bool }
```

In my custom plugin by invoking
```
onTransitionSuccess(toState, fromState, opts)
```
I was getting different results from `opts` for different cases.

Given that I don't pass this object (for example when using the browser plugin) I first tough that this config object is related to the general router config params, in particular to `allowNotFound`.

But then I went a bit deeper into the browser plugin code and I saw that for some cases it adds `reload: true, replace: true` and for others `replace: true`.

Could you please clarify what is the default value of `opts` when not passed explicitly (or when passing an empty object `{}`) to `router.navigate` and what is its relation with the `allowNotFound` router option? 

Apparently this depends on the plugin and navigation results (same route/ if default is set/ ectr), right?

**Comment by troch** [comment]
`{ reload: false, replace: false }`

- reload: the transition instead of being from node A to B, is from `null` to B. In practice you can use it to "reload" a route and force the router to re-evaluate `canActivate` functions and re-fetch data. When passed to `onTransitionSuccess`, at that time the "reload" has already happened.
- `replace`: only  used by the browser plugin for now, but could be used by any history plugin: instead of pushing to the history, replace current state.

There isn't a relation with `allowNotFound`: `allowNotFound` is a router option, `reload` and `replace` are transition options. `allowNotFound` has no relation with `router.navigate`, it is only used for unmatched URLs to be represented as a state rather than ignored. If you pass an incorrect route name to navigate, it will throw.

I'll add to the list of things to do for v5 to add explicit defaults.
