### ISSUE TITLE
canDeactivate for nested routes

### ISSUE THREAD

**Issue by grumd** [router5/router5#163]
https://github.com/router5/router5/commit/1239890

You made this fix for canActivate, but not for canDeactivate. Can you pls do the same for canDeactivate?

**Comment by troch** [comment]
Clicking the commit hash link, I'm not sure what fix it refers to. Can you explain a bit more?

**Comment by grumd** [comment]
When using `children` in routes config, `canActivate` would not register for nested routes (children routes). Commit hash I provided fixes it, but only for `canActivate`. It's still not fixed for `canDeactivate`. Any route that's inside of `children` attribute of other routes will not get its `canDeactivate` registered.

**Comment by troch** [comment]
`canDeactivate` handlers are not registered with the router when specified on route objects (only `path`, `name`, `canActivate` and `forwardTo` are taken into account)

**Comment by grumd** [comment]
Why is that though?

**Comment by troch** [comment]
Because `canActivate` is inherently linked to the external scope of a view, while `canDeactivate` is about the inner scope. That was an early decision. You are welcome to raise a PR, here is where it should happen: https://github.com/router5/router5/blob/master/packages/router5/modules/create-router.js#L107-L112

**Comment by troch** [comment]
Closing for now
