### ISSUE TITLE
Sync vs Async complication

### ISSUE THREAD

**Issue by ivan-kleshnin** [router5/router5#17]
Router5 contains functions which can be either sync or async. This is not only strange (what occurs on error if callback is not provided? only source code can answer...), but also leads to errors. There are a plenty of them already.

```js
navigate(name, params = {}, opts = {}, done) { // syntax error!
  if (!this.started) {
    done(constants.ROUTER_NOT_STARTED) // forgot to wrap in if (done)
    return
  }
  ...

  if (!path) throw new Error(`Could not find route "${name}"`) // why this error not passed to done?!
}
```

I think this is overcomplicated and we need to drop either sync or async versions in each case.
What errors can occur at the transition time btw? 
I see in code it's something about cancelation but is this really an error to bother?
Can't we just ignore some corner cases and make navigation sync-only?

**Comment by troch** [comment]
Hi @ivan-kleshnin,

- For sync and async, I don't see what the problem is. `navigate()` returns a cancellation function, and a `.done(err, state)` callback can be passed to it. A transition is a synchronous or asynchronous process depending on the steps it is made of: canDeactivate, canActivate, onTransition, etc... `router5` lets developers use both and can track completion of async or sync functions. I don't think code is not overcomplicated.
- Errors which can occur at transition are: `SAME_STATES`, `CANNOT_DEACTIVATE`, `CANNOT_ACTIVATE`, `TRANSITION_ERR`, `NODE_LISTENER_ERR`
- When the router instance is not started, an error should be thrown instead of calling done. This will be corrected. Only errors occurring at transition time will be passed to done. This is why the "Could not find route..." is not passed to done.

**Comment by ivan-kleshnin** [comment]
> A transition is a synchronous or asynchronous process depending on the steps it is made of

I can't remember single other library which has the API of such kind. If it's naturally async why pretend it can be sync "in some cases"? This only overcomplicates thing. Maybe in your API alone it's still decent complexity but when people wrap your library in other library (and routers are meant for that, right?) complexity continues to grow because some libs have fundamentally different requirements for sync and async and the fundamentally can't express it as the same function. So the create navigateSync / navigateAsync and the whole picture is starting to decay.

**Comment by troch** [comment]
I don't understand what is bothering you, neither do I understand what you want.

- The reason for having a `done` callback is because `navigate` returns a cancellation function
- By default, navigate is a synchronous process. `done` will be called on the same call stack
- `navigate` can become an asynchronous process depending on the "middlewares" that can compose a transition and which are defined by the developer (like data loading for example).

For wrappers around router5, they only want to know if a transition was successful or not by providing a callback. I don't think that the fact that callback is called on the same stack or later matters.

**Comment by troch** [comment]
http://localhost:8080/docs/transition.html

**Comment by ivan-kleshnin** [comment]
Thank you for explanation @troch. I'm not totally agree, but I need more first hand experience with your lib to argue "for" or "against". Let's close this for now.

**Comment by troch** [comment]
A test runner (jasmine 2.0) or a task runner (gulp) take similar approaches.
