### ISSUE TITLE
Root node documentation

### ISSUE THREAD

**Issue by ivan-kleshnin** [router5/router5#21]
http://router5.github.io/docs/configuring-routes.html says 

> If you pass to Router5 an array, it will automatically create a rootNode with an empty name and empty path (new RouteNode('', '')), which is the recommended way.

However it is impossible to either `new Router5({name: '', path: ''})` or `router.addNode('', '')` because of **Uncaught Error: Route constructor expects routes to have an name and a path defined.**.

Not to mention that '' can't match anything. 

So it is both:
1) recommend to use empty name and route for root node 
2) which is impossible to implement

**Comment by troch** [comment]
The use of a not unamed root node is not recommended, not tested and therefore not documented.

The only way to do it is to path a RouteNode object to the constructor, otherwise it will default to `this.rootNode = new RouteNode('', '')`.

- `new Router5({name: '', path: ''})` will create an unamed root node and then tried to add an unamed route to the tree => __error__
- `router.addNode('', '')` => constructor has already been called, same as above

**Comment by ivan-kleshnin** [comment]
Don't you think you need to refactor documentation?

**Comment by troch** [comment]
It is part of the roadmap to "1.0.0" to improve documentations. Please raise documentation issues [here](/router5/router.github.io/issues)

**Comment by ivan-kleshnin** [comment]
> It is part of the roadmap to "1.0.0" to improve documentation

Good to know.

> Please raise documentation issues here

Link is broken :(

**Comment by troch** [comment]
Fixed
