### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by aksel** [router5/router5#227]
I think status codes on route objects would be a good addition.

An example use case would be 404 status code on 404 pages.
This helps with analytics, and helps crawlers understand the site better.

One issue I can think of at the moment is with regards to child routes. If both parent and child have status codes, whose status code do you use? The child's, in my opinion, but it still disregards the parent status code. Though I can't exactly imagine a scenario where child and parent have differing status codes.

I have written a middleware to handle adding the status code to the state, but I think it might benefit to be part of the core.

If no status code is specified, it should default to 200.

**Comment by cyberhck** [comment]
@aksel I assume you're talking about status code while doing SSR? I'm interested to know how you're handling that :) can you provide a overview on how you're getting status code from router?

**Comment by troch** [comment]
@cyberhck yes, status code while doing SSR

Hi @aksel 

Making it part of the core would be tricky because router5 is not opinionated when it comes to data loading. As you noted it: you could have nested routes, or you could have multiple calls on the same route node, etc... In most cases, there is one single call (fetching data from an ID'd resource) which can change the status of a server-side response.

That said, I'm very interested in looking at what you have come up with, and hearing more of your thoughts

**Comment by aksel** [comment]
@troch Yeah I suppose so. And the middleware handles it exactly as how I want it anyhow. 😃  

[Here's a gist of routes with status codes.](https://gist.github.com/aksel/31c05995e8dc5e8d5b6f7bb0c71cf2b4)

@cyberhck In the not-so-distant future, after I am done with my current task at work, I am going to make an example repo. Isomorphic React, with Redux and router5.
I can ping you when it is done 😃

**Comment by cyberhck** [comment]
Okay, 🙂 looking forward to it

**Comment by aksel** [comment]
@troch 
@cyberhck 

I have made the example project 😃 
It could still use some documentation and such, and the frontend is not exactly _pretty_, but the basic stuff is there. Any feedback is greatly appreciated.

Link: [router5-react-redux](https://github.com/artboost/router5-react-redux)
