### ISSUE TITLE
Revert url on cancelling transition after manual url change.

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#249]
Seems like if I throw any string in middleware to cancel transition after url was changed manually, url stuck on that manual input.

For example I have a list page with pagination `/#/list?page=10`, and if user manually enters `/#/list?page=100`, but number is out of bounds of allowed pages, I cancel route in middleware. Browser url still contains page=100, but page=10 is expected.

Probably it's related to #177

**Comment by troch** [comment]
When the address is manually changed, it adds a new history entry. If the edit is after the `#`, it creates a popstate event.

- When a new entry is added, it can only be replaced: replacing it with the previous URL would create a doubled entry in the history (users need to click the back button twice to go back to the real previous URL)
- I don't know what the previous URL was: in case of URLs after the `#`, I can't know if the popstate event was caused by the back button, the forward button or a manual edit. And in case of an URL change, it causes a page unload and load.

From my own experience, outside-the-page interactions (back / forward / edit) can't be cancelled (from an event perspective) and aren't worth fighting against. The best solution (again from my experience) is to display an error / not found message.

**Comment by klimashkin** [comment]
But how do I know in middleware if it is normal transition (by navigate event) or manual by url change to decide if it's ok to cancel?

If in that case I throw redirect object with {name: 'list', page: 10}, then on next middleware call I get `null` fromState.

**Comment by klimashkin** [comment]
Oh, If I throw string just to cancel route in case of manual input I get middleware called second time with empty fromState. If I throw string on normal navigate event I don't get second middleware call

**Comment by troch** [comment]
> But how do I know in middleware if it is normal transition (by navigate event) or manual by url change to decide if it's ok to cancel?

There should be a `source` property in `meta` saying `popstate`. But again a popstate event can be either a back, forward or manual change

**Comment by troch** [comment]
> If in that case I throw redirect object with {name: 'list', page: 10}, then on next middleware call I get null fromState.

I'll have a look

**Comment by klimashkin** [comment]
Ok, I've found workaround for this issue and #195 (seems like 195 also caused by url change from out of Router5 world by pressing history buttons). It's a bit hacky, but works. My thoughts is that calling history.replaceState that leads to duplicate items in history is better than broken state : )

```javascript
async routeMiddleware(toState, fromState) {
  if (this.replaceURLWith) {
    // If we cancel transition which was caused by manual url change, Router5 will call middleware one more time with 'null' fromState
    // To workaround that throw string one more time to cancel for sure
    // https://github.com/router5/router5/issues/249
    // https://github.com/router5/router5/issues/195
    history.replaceState(null, document.title, this.replaceURLWith);
    this.replaceURLWith = null;

    throw 'Broken transition canceled';
  }

  this.fromState = fromState

  //... 
  //A lot of asynchronous logic that leads to cancelling transition... 
  //...

  if (location.href.endsWith(toState.path)) {
     // If location equals to target state, means url has been changed from the outside (manually or by browser history buttons)
     // In that case replace history state to rollback to previous url manually on next middleware call which will happen with empty fromState in this case
     this.replaceURLWith = '#' + fromState.path;
  }

  throw 'Transition canceled'; // eslint-disable-line no-throw-literal
}
```

Let me know if you think it's not enough as workaround for now

**Comment by troch** [comment]
Cancellation is not possible with the history API, and as a result any attempt to cancel forces us down the way of additional history entries. I started this project naively thinking `canDeactivate` was a good idea until I had to make it work with the browser plugin. I now thing that navigation should not be prevented, and that content should adapt (displaying a not found view, a login form, the requested content...).

So any workaround should be user land rather than included in the router. The browser plugin has a `replaceHistoryState` method that you can use to hack things: https://router5.js.org/api-reference#replacehistorystate.

**Comment by klimashkin** [comment]
> I now thing that navigation should not be prevented, and that content should adapt (displaying a not found view, a login form, the requested content...).
Please, don't change that. Preventing navigation is the reason why we use router5, not other routers : )

**Comment by troch** [comment]
Don't worry I wasn't suggested that I was going to change it or remove it, it's great as it is. I was simply pointing the limitations (caused by the browser history) and that those limitations caused me to change the way I personally approach things in the app I work with. But the problem goes away or is different in other environments (electron, RN) and router5 is not meant to only work in browsers.
