### ISSUE TITLE
TypeScript typings for RouterState

### ISSUE THREAD

**Issue by TroySchmidt** [router5/router5#250]
If a component is written with Props interface that extends ```RouterState``` then all the parameters of RouterState are required for the component in jest testing.  Instead of making the properties ``` | null``` they should be optional like ```route?: State```.
Can that be tested to make sure it doesn't break anything else internally?

**Comment by zaeleus** [comment]
These actually used to be optional but changed in #224. The problem stems from the design of (redux-)router5. It does explicitly set `routerState` to `null`, not `undefined`: [reducer initial state](https://github.com/router5/router5/blob/4d4fc58f0d5f9a2f1cbaf321fbc1f01cc021ee0e/packages/redux-router5/modules/lib/router5Reducer.js#L3-L8), [router initialization](https://github.com/router5/router5/blob/4d4fc58f0d5f9a2f1cbaf321fbc1f01cc021ee0e/packages/router5/modules/create-router.js#L28) and [router stop](https://github.com/router5/router5/blob/ef66c71d4dd502c4fc4338f5fcc3a1f84c6e8c85/packages/router5/modules/core/router-lifecycle.js#L127).

You would be forfeiting correctness making them optional, particularly since `null` and `undefined` are two distinct types. Unfortunately, TypeScript treated them the same until 2.0 with the introduction of [`strictNullChecks`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#--strictnullchecks) (or [`strict`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#new---strict-master-option) is 2.3).

I would suggest extending `Partial<RouterState>` if you want those properties to be optional and can guarantee the shape of the object.

**Comment by TroySchmidt** [comment]
Ahhh.. Okay that is unfortunate.  I cannot extend Partial<RouteState> or I am running into Type issues using the selector in the connect statement since I have the return typing enforced so I don't miss adding the selector to get back state needed or misspell or capitalize something there.  I am using MaterialUI v1.x package and in the pattern I have already I have a pattern to enforce typings internal to the component that aren't exposed externally.  This is mainly for "magic" like the router state being supplied external to the component and it is akin to it being injected almost.  So the component itself sees the route property from ```RouterState``` but the external type doesn't include those properties.  This way the component in Storybook and Jest doesn't need those parameters supplied.
You can close this.
