### ISSUE TITLE
Open route in new tab by pressing Ctrl/Cmd/Meta

### ISSUE THREAD

**Issue by vvhsk** [router5/router5#257]
Hi to all.

Is there any default method to open navigate (navigateTo) links in new tab when pressing ctrl, cmd or meta key?

**Comment by troch** [comment]
Ctrl or Cmd + click on an hyperlink opens a new tab, so it's not something your router can do (and should do) something about.

**Comment by bradrydzewski** [comment]
@troch I came to this issue because I was trying to figure this out as well

If I use `cmd+click` in the [redux demo](http://router5.github.io/docs/with-react-redux.html#/inbox) it does not open in a new window as I would have expected.

I was looking through the code, and if I understand correctly, the ability to open in a new window with `ctrl+cmd` is predicated on your using a component for links that inherits from `<BaseLink>` (react) which handles the click event and checks for keys pressed [1]. So if you are using the redux router without react (let's say polymer+redux or lit-html+redux) it looks like a custom element would be required to implement the same sort of on-click handling. Is my understanding correct?

[1] https://github.com/router5/react-router5/blob/master/dist/es/BaseLink.js#L50

**Comment by troch** [comment]
Oh I see, it is because `.preventDefault` is called, and there is no check for combo keys being pressed.

**Comment by vvhsk** [comment]
@troch 
Thanks, I understood this later after created the issue, I made this behaviour with custom handler. I had little misunderstanding that only `<BaseLink>` can handle key pressed in redux demo (as @bradrydzewski described). Maybe this should be documented somewhere?

**Comment by troch** [comment]
I think that's because the examples have not been updated for a while, but links have been checking for ctrl / meta / alt keys for a while now (https://github.com/router5/router5/blob/master/packages/react-router5/modules/BaseLink.js#L58-L61).
