### ISSUE TITLE
React Native + Redux?

### ISSUE THREAD

**Issue by corysimmons** [router5/router5#259]
Would love to see an example with both.

**Comment by corysimmons** [comment]
No helpers for RN. Stuck with react-router... -_-

**Comment by troch** [comment]
What helpers would you be looking for? AFAIK, the only thing you need is a history plugin?

**Comment by corysimmons** [comment]
tbh after posting i realized i probably didn't need to be tracking nav state in redux.
i think other people have raised reasons for wanting it https://twitter.com/satya164/status/952291726521024512 but i don't have a need right now. Sorry

**Comment by troch** [comment]
That's right you don't need to track it in redux. But redux is universal so it doesn't impact native integration, whether you do it or not.

**Comment by troch** [comment]
Yes, `react-router5` is for react, I should maybe create a `react-native-router5`

**Comment by corysimmons** [comment]
@troch Yeah that'd be cool. Let me know if you aren't super comfy with React Native and I can help out.

**Comment by troch** [comment]
Sure, I could do with some help.

Whether react-native or react, decision to integrate routing state with redux is down to personal preference. From personal experience, I think you get cleaner patterns without, because having it in redux can lead to routing context leaking to components which shouldn't be aware of it. But as I said, it is down to personal preference...
