### ISSUE TITLE
Consider rephrasing Universal applications as Isomorphic applications

### ISSUE THREAD

**Issue by RickWong** [router5/router5#26]
Disclaimer: I know that this kind of request is unpopular. I'm not trying to annoy anyone.

I'm the maintainer of an isomorphic starterkit for React. Some time ago I seriously considered renaming my project to "universal starterkit". However I then came across the following article: https://medium.com/@ghengeveld/isomorphism-vs-universal-javascript-4b47fb481beb Now I strongly think that even though Javascript *code* can be universal, we should keep calling the applications that do run similar, but divergent code between server and client, *isomorphic*.

**Comment by troch** [comment]
Hello @RickWong,

Thank you for your comment and your link. To be honest, I don't find these two terms describe well what this router is. This library cannot be used outside the browser, because most its functionalities cannot be enabled. If you wanted to run an application on the server side with it, you would use its sole dependency `route-node` and build on top of it.

What this does: it supports starting your application on the server-side so you can get a starting route for pre-rendering your view. So basically I think it would need a new terminology.

**Comment by RickWong** [comment]
Thanks for the explanation.
