### ISSUE TITLE
Better Way of Adding Listeners - Discussion/Proposal

### ISSUE THREAD

**Issue by JonathanWolfe** [router5/router5#28]
Currently, my router resembles the following:
```js
const router = new Router5( [], {
		useHash: true,
		trailingSlash: true,
		defaultRouter: 'home',
	} )
	.addNode( 'home', '/' )
	.addNode( 'login', '/login' )
	.addNode( 'signup', '/signup' )
	.addNode( 'profile', '/profile', authenticatedRoute )
	.addNode( 'users', '/users', authenticatedRoute )
	.addNode( 'user', '/user/:id', authenticatedRoute )
	.addNode( '404', '/404' );

router.addRouteListener( 'home', ( toState, fromState ) => mountPage( 'app' ) );

router.addRouteListener( 'login', ( toState, fromState ) => mountPage( 'login' ) );
router.addRouteListener( 'signup', ( toState, fromState ) => mountPage( 'signup' ) );

router.addRouteListener( 'users', ( toState, fromState ) => mountPage( 'list-users' ) );
router.addRouteListener( 'user', ( toState, fromState ) => mountPage( 'user' ) );
router.addRouteListener( 'profile', ( toState, fromState ) => mountPage( 'user' ) );

router.addRouteListener( '404', ( toState, fromState ) => mountPage( '404' ) );
```

The route listener portion feels cumbersome. I thought that RouteNode would be the right way to go about it, but it doesn't have this capability.

What'd I'd like to do is be able to is sort of combine both RouteNode and the POJO syntaxes together to make it more powerful:
```js
const router = Router5( [
	routeNode( {
		name: 'home',
		path: '/',
		canActivate: ( toState, fromState ) => authenticatedRoute,
		onRoute: ( toState, fromState ) => {
			// Equates to .addRouteListener
		},
		onNode: ( toState, fromState ) => {
			// Equates to .addNodeListener
		},
		onNavigate: ( toState, fromState ) => {
			// Equates to .addListener
		},
	} ),
] );
```

**Comment by troch** [comment]
A few questions before trying to give an educated answer:
- What do you use for your view?
- What does `mountPage(...)` do?
- Are your routes flat?

**Comment by JonathanWolfe** [comment]
- I'm using [Riot.JS](http://riotjs.com/) for my views. 
- `mountPage` is just the method I wrote to unmount the current page and mount the next one.
- No, my routes aren't completely flat

**Comment by troch** [comment]
The three types of listeners (addListener, addNodeListener, addRouteListener) were designed to be called by components. Because components will appear and disappear during the course of an application runtime, I think it would be confusing to be able to add them when configuring a router. This is especially true for node listeners which are designed to be used to update a view (the other ones are there to help with edge-cases and "side updates" of your view).

My idea is to try to keep router5 as lean as possible, and have it as a base to create more complex systems. My current thought process is to make listeners an optional middleware rather than integrating them further with routes, and have the router only taking care of updating a piece of state.

Another middleware which could be added is to have onActivate / onDeactivate functions (for data loading / unloading purposes). That might be more what you are trying to achieve with something like `onNavigate`.

So far router5 supports the addition of a single middleware (you obviously compose functions to create a middleware). I am still thinking about what to do and where to go, but I am more looking at decoupling things.

**Comment by troch** [comment]
Hi @JonathanWolfe, I don't know where you are at with your use of router5 with riot.js. Version 1.0.0 of router5 will be published during the week, it introduces the concept of router plugins where you can trigger operations on start, stop, transition start, transition error, transition success... Each plugin receives the router instance which allows us to decorate it with some methods. This is what [router5-listeners](https://github.com/router5/router5-listeners) does. If you want a specific API to suit riot.js, then you'll then be able to implement it. Multiple middleware functions are also supported with router5@1.0.0

**Comment by JonathanWolfe** [comment]
Cool. I've got a light load at work so I'll look into it.

**Comment by troch** [comment]
Router5 v1.0.0 released. Closing this issue for now.
