### ISSUE TITLE
Transition for same route name with different params by back and forward buttons

### ISSUE THREAD

**Issue by max-mykhailenko** [router5/router5#37]
Back and forward buttons doesn't calls transition route

- canary 49
- router5
- redux-router5

**Comment by troch** [comment]
Can you give me a little bit more information about your routes, and what route you are trying to transition to and from?

Also, can you confirm you are using the latest version (1.2.0)?

**Comment by max-mykhailenko** [comment]
Yes, I have latest versions
```
├── router5@1.2.1
├── router5-history@1.0.1
```

Router configuration

```
const router = createRouter(
  [
    {
      name: 'home',
      path: '/home',
    },
    {
      name: 'product',
      path: '/product/:productID',
      children: [
        {
          name: 'calculator',
          path: '/program/:programID/?:elements&:variations',
        },
      ],
    },
  ],
  {
    defaultRoute: 'type.calculator',
  }
);
```

Change route from 

http://rgb-lab.loc/ru/prices/calculator/#!/product/36/program/1/?elements=44-55-53&variations=5
to
http://rgb-lab.loc/ru/prices/calculator/#!/product/36/program/1/?elements=44-55-51&variations=5

`NavigateTo` from `router5-redux` works only when set `reload: true`

How I can improve my code for working without `reload: true` or when press browsers buttons

**Comment by troch** [comment]
I think it has to do with query parameters. I'll need to check a few things and I'll come back to you.

**Comment by max-mykhailenko** [comment]
@troch hi, maybe I can help you with this task?

**Comment by troch** [comment]
Yes, that would be helpful if you had some code which could demonstrate this.

The router can issue a `SAME_STATE` error if trying to navigate to the same state. Two states are considered different if all parameters are not the same. The only thing I can think of is: how are you creating / handling links? For example if you use `router.navigate(...)`, don't forget to call `.preventDefault()` on the click event otherwise it will generate a popstate event and then mess up your history (giving you the impression back and forward buttons don't work).

**Comment by troch** [comment]
OK, I found the issue. I wasn't looking at the right place. It is an issue with router5-history, https://github.com/router5/router5-history/blob/master/modules/index.js#L28 (last argument of `areStateEquals` should be `false`).

**Comment by troch** [comment]
router-history 2.0.1 released earlier

**Comment by max-mykhailenko** [comment]
Thanks!
