### ISSUE TITLE
Dealing with universal route

### ISSUE THREAD

**Issue by akoenig** [router5/router5#49]
First of all: thanks for putting so much effort into router5 - it's beautiful!

We are building a pretty large app with react + redux and router5 as the routing backbone. At the moment we are struggling with the question how to deal with a universal dispatch mechanism which will be triggered before the very first route transition. We have to perform several steps while bootstrapping the application and want to display some kind of splash screen while performing those steps. How would you realize such a use case?

Thanks in advance :)

**Comment by troch** [comment]
Thanks for your kind words. Not sure I fully understand what you are trying to achieve. By "universal", do you mean server-side? Do you want to pre-render on the server-side a splash screen (with or without pre-loaded data) and then do some more loading in the browser?

**Comment by akoenig** [comment]
True, `universal` is some kind of misleading :) What I want to achieve is to render a splash screen component while bootstrapping the application on the client. This splash screen should be visible while checking the JWT, loading the user profile etc. When those steps are performed, I want to dispatch the desired route. I hope this clarifies the scenario a little bit :)

**Comment by troch** [comment]
So I can't give you a precise answer, because there are many many ways data can be handled. router5 will bring you part of your state: your route name and params. Then you need to load data related to the components you want to show.

When you load data, you can do it:
- From a router5 middleware
- From a redux middleware
- From components (using higher-order components, or something like redial from Mark Dalgleish)

Because you use redux, your redux state is your only source of truth. I recommend introducing as little coupling as possible with the router, and therefore favour loading data at the component level rather than the route level: i.e. new state from the router will hit your redux state, causing you to display somewhere a new component. That component can be enhanced / wrapped with a higher-order component taking care of dispatching loading data actions / displaying loading feedback while data loads. I find myself moving more and more towards those techniques, I have some writing / documentation effort to make.

As I said, there are different approaches one can take. Find the one you are most comfortable with!

**Comment by akoenig** [comment]
Hey @troch, thanks for your response and sorry for my late reply. I developed a solution in which I established an own redux middleware for triggering the "boarding" process and a splashscreen component which sits directly in the root component (same level as the `{children}`). The splashscreen is connected to the store and hides itself when the boarding process is done.

So in the end there is no `router5` involvement here and I close this issue / question :)

Thanks for all.
