### ISSUE TITLE
Default children routes

### ISSUE THREAD

**Issue by akoenig** [router5/router5#52]
I'm dealing at the moment with the question how to deal with children nodes which acts as default routes under the parent. Consider the following routes definition:

```js
const routes = {
    'system': '/system',
    'system.cpu': '/cpu',
    'system.memory': '/memory',
    'foo': '/foo'
};
```

Whereas `/system` is the `defaultRoute`. What I want to achieve is that if the user navigates to `/system` that she gets automatically redirected to `/system/cpu`.

Could you point me in the right direction? Ah, btw. I'm using `router5` in combination with `redux-router5`.

Thanks in advance :)

**Comment by troch** [comment]
There are 3 ways you can do this.

__1. Redirecting after an error__

You fail the current transition and redirect to `sytem.cpu`. The only caveat is if you have some sort of general error handling.

Note: `store` is the first attribute of `canActivate` since you are using redux.

```js
router.canActivate('system', (store, toState, fromState, done) => {
    if (toState.name === 'system') done({ redirect: { name: 'system.cpu' }})
    else done(null, toState)
})

// Or

router.canActivate('system', (store, toState) =>
    toState.name === 'system'
        ? Promise.resolve()
        : Promise.reject({ redirect: { name: 'system.cpu' }})
)
```

__2. Redux middleware__

If you use actions for triggering router transitions (I usually directly use the router instance), you can replace the middleware provided by `redux-router5` by a custom one which would do the same thing, except if it receives an action for navigating to `system`, it would navigate to `system.cpu`.

__3. Decorate your router__

You can decorate `router.navigate` (you would need to decorate `_transition` too as it is used by the history plugin) so it navigates to `system.cpu` instead of `system`.

**Comment by troch** [comment]
Closing this for now.

**Comment by hellosmithy** [comment]
Just a note on the `canActivate` approach - I don't believe this works when transitioning from children of the route to the index e.g. `system.memory` to `system` as the route is already "active"

**Comment by troch** [comment]
@hellosmithy that is correct, so my first example is incorrect.

Best way to approach this problem though is I believe with a plugin decorating the router instance, something [router5-persistent-params](router5/router5-persistent-params) does.

**Comment by hellosmithy** [comment]
@troch how would one go about doing this? It looks like the plugin lifecycle callbacks such as `onTransitionStart` provide immutable route objects. Is there anyway to prevent or redirect a transition from these callbacks?

**Comment by troch** [comment]
onTransitionStart, Success, Error or Cancel are "after the facts" informative callbacks. They are hooks you can use to trigger actions (side-effects), and don't have control over a route transition.

You can redirect when you fail a transition: in a `canActivate` handler or within a middleware.

For the problem described in this, I would use a plugin which would decorate (aka monkey patch) `route.navigate` (if trying to navigate to `system`, it will silently call the original `route.navigate` with `system.cpu`).

**Comment by thupi** [comment]
I am trying to solve same kind of problem but hasn't been able to solve the problem yet. 

I am using switch statments in order to render the correct component. Right now i am just using the defualt case in the switch statement but the  leads to some wired behavior when transtioning from a nested child route to another while router5 thinks the current page is the parrent. 

Isn't this a very common routing method? Wouldn't it make sense to make a easier way of achiveing this :-) ?

**Comment by troch** [comment]
Do you have code I can look at? I'm not following very well your description.

**Comment by thupi** [comment]
Yeah :-) It's hard to explain in words :-)

`import * as React from 'react';
import { routeNode, IRouteNodeProps } from 'react-mobx-router5';

// Constants
import { ROUTE_PATHS, ROUTE_NAMES } from '../../constants/routes';

// Components
import RouteReplace from '../../components/RouteReplace';

import AppNetworkPeople from '../AppNetworkPeople';
import AppNetworkQuestions from '../AppNetworkQuestions';
import AppNetworkAdministration from '../AppNetworkAdministration';

//
export interface IProps extends IRouteNodeProps {}

class Router extends React.Component<IProps, {}> {
  render() {
    if (!this.props.route) {
      return <h1>Not Found</h1>;
    }
    const segment = this.props.route.name.split('.')[2];
    switch (segment) {
      case ROUTE_NAMES.APP_NETWORK_PEOPLE:
        return <AppNetworkPeople />;
      case ROUTE_NAMES.APP_NETWORK_QUESTIONS:
        return <AppNetworkQuestions />;
      case ROUTE_NAMES.APP_NETWORK_ADMINISTRATION:
        return <AppNetworkAdministration />;
      default:
        return (
          <RouteReplace
            routeName={ROUTE_PATHS.APP_NETWORK_PEOPLE}
            routerParams={this.props.route.params}
          />
        );
    }
  }
}

export default routeNode(ROUTE_PATHS.APP_NETWORK)(Router);
`

I am using mobx-router5 and react-mobx-router5 in order to make the data from router5 observable :-)

In the code i am trying to have a way to have one of the children to act as a default route. Right now the RouteReplace component is just redirecting the route to the child route. However, i think i would be very nice addition to router5 if something like this would be possible in the config :-)

**Comment by troch** [comment]
OK, so what you want is a fallback route? router5 is about state / view separation: it looks after your routing state, and then you do the state / component mapping. There are a couple of ways you can have a default state (that you then map to a default route) or redirect state:
- `defaultRoute` option (http://router5.github.io/docs/router-options.html)
- You can allow not found states (`allowNotFound` option, see link above)
- You can redirect during a transition using a middleware (so you avoid a navigate with `replace` set to `true`): http://router5.github.io/docs/custom-errors.html

**Comment by thupi** [comment]
@troch The defaultRoute option looks like the easiest implemetation but the router option mentioned only works for the root right :-) Would something like that be possible in the nested routes :-) Mayby something like: ```
{name: 'route1', path: '/route1', defaultRoute:'route1-1', children: [...]}
```

**Comment by troch** [comment]
The defaultRoute is only used when failing to match a route. From your code above, is `forwardTo` the right option for you?

**Comment by thupi** [comment]
Ahh okay :-) I might just need the forward to then :-) ! Thanks :-) !
