### ISSUE TITLE
Unified way to import plugins

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#80]
Now loggerPlugin is reexported by router5 itself, so I can write
`import createRouter, {loggerPlugin} from 'router5';`
And it looks good, but newly moved browser and listeners plugins can be imported only through their paths.

Would be great to have one way

**Comment by troch** [comment]
You can import the logger plugin the same way you import other plugins. I didn't want to remove it from the main package for UMD users (AMD, globals) as otherwise I would need to create an UMD build for the logger plugin only. Since it is a tiny debugging utility, I think it's preferable to have it included in the main package and available when needed.
