### ISSUE TITLE
_meta & meta of fromState

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#85]
Hi!
When I call `navigate` for the first time (through redux action), I get this in console:
```
[router5.transition-path] Some states are missing metadata, reloading all segments
```

Seems like because very first `fromState` contains `meta` prop instead of `_meta`:
https://github.com/router5/router5/blob/646bd5b2dcbeb06d16fdf280878c68fb9042706a/modules/create-router.js#L126

**Comment by troch** [comment]
Hey,

It has been fixed (4.1.1). It is `meta` now (was mentioned in v4 release notes), however there was a bug in router5.transition-path which was still looking for _meta. So that should work and navigating to the same states with different params should not cause the root node to receive the update anymore.
