### ISSUE TITLE
lazy loading modules on state change

### ISSUE THREAD

**Issue by Hotell** [router5/router5#97]
React router has [`getComponent`](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#getcomponentnextstate-callback) , ui-router [`lazyLoad`](https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#lazyload). 

Is there some way how to achieve this with router5?

This is critical feature for huge apps which needs code splitting.

thanks

**Comment by troch** [comment]
router5 is not linked to components and only concerned with state changes, not rendering.

That said, a few things:
- You are free to do code splitting, nothing is preventing you to do it
- You should treat code as data: in other words, treat loading of chunks the same way you treat loading data: either with higher-order / wrapper components, or you can use router5 middleware functions. With middlewares, you can call a `done` callback or return a promise, making them perfectly usable with `require.ensure` or `System.import`. Blocking a route transition is not necessarily great for UX.
- There are emerging techniques of anticipated loading rather than lazy loading (i.e. from a view, you load chunks where a user is likely to go next).

**Comment by troch** [comment]
I added a chunk loading section in async data guide: [http://router5.github.io/docs/async-data.html#chunk-loading](http://router5.github.io/docs/async-data.html#chunk-loading)

**Comment by Hotell** [comment]
thx so much @troch you rock!
